export enum MensagemEnum {
  COMPRA_EFETUADA_COM_SUCESSO = "Compra efetuada com sucesso.",
  COMPRA_SEM_QUANTIDADE_ITEMS = "Por favor, selecione a quantidade de produtos desejados.",
  DESEJO_REMOVER_ITEM = "Deseja remover o item?",
  EFETUE_LOGIN = "É necessário efetuar o login para realizar essa ação.",
  DADOS_CLIENTE_INVALIDO = "Preencha todos os dados do seu perfil para realizar essa ação .",
  FALHA_AO_RECUPERAR_CARRINHO = "Falha ao recuperar dados do carrinho",
  CARRINHO_VAZIO = "O carrinho está vazio.",
  PAGAMENTO_APROVADO = "Seu pagamento foi aprovado. Muito obrigado por ser nosso parceiro.",
  PAGAMENTO_PROCESSAMENTO = "Seu pagamento está em processamento. Vamos te dar um retorno em breve.",
  PAGAMENTO_REJEITADO = "Aconteceu algo de errado e seu pagamento foi rejeitado. Por favor, tente novamente",
  PREENCHA_TODOS_CAMPOS = "Preencha todos os campos.",
  PRODUTO_INDISPONIVEL = "O produto está indisponível.",
  PRODUTO_EXISTE_CARRINHO = "O produto já está dentro do carrinho.",
  PRODUTO_ADD_CARRINHO = "O produto foi adicionado ao carrinho.",
  NENHUM_CAMPO_FOI_ATUALIZADO = "Nenhum campo foi atualizado.",
  VALOR_PAGAMENTO_INVALIDO = "Valor para pagamento precisa ser maior que zero.",
}
