export enum RotasEnum {
  ADMIN = "admin",
  ALUGAR = "como-alugar",
  HOME = "home",
  BRINQUEDOS = "brinquedos",
  BRINQUEDOTECA = "brinquedoteca",
  CARRINHO = "carrinho",
  CONTATO = "contato",
  CONCLUSAO = "conclusao",
  COMPRAS = "compras",
  CRESCER_BEM = "https://crescerdf.com/",
  DESCRICAO = "descricao",
  DIALOGANDO = "dialogando",
  HIGIENIZACAO = "higienizacao",
  IDADE = "por-idade",
  SEGURANCA = "seguranca",
  QUEM_SOMOS = "quem-somos",
  NOVIDADES = "novidades",
  CADASTRO = "cadastro",
  // PRODUTOS = "produtos",
  PROMOCOES = "promocoes",
  TERMOS = "termos-uso",
  LOGIN = "login",
  NONE = "",
  LOJA = "loja",
  FULL = "full",
}
