export enum RotasEnum {
  HOME = "home",
  CARRINHO = "carrinho",
  CONTATO = "contato",
  CONCLUSAO = "conclusao",
  COMPRAS = "compras",
  DESCRICAO = "descricao",
  SEGURANCA = "seguranca",
  QUEM_SOMOS = "quem-somos",
  NOVIDADES = "novidades",
  CADASTRO = "cadastro",
  PRODUTOS = "produtos",
  PROMOCOES = "promocoes",
  LOGIN = "login",
  NONE = "",
  LOJA = "loja",
  FULL = "full",
}
