export enum RotasEnum {
  ADMIN = "admin",
  HOME = "home",
  BRINQUEDOS = "brinquedos",
  BRINQUEDOTECA = "brinquedoteca",
  CARRINHO = "carrinho",
  CONTATO = "contato",
  CONCLUSAO = "conclusao",
  COMPRAS = "compras",
  CRESCER_BEM = "https://crescerdf.com/",
  DESCRICAO = "descricao",
  SEGURANCA = "seguranca",
  QUEM_SOMOS = "quem-somos",
  NOVIDADES = "novidades",
  CADASTRO = "cadastro",
  // PRODUTOS = "produtos",
  PROMOCOES = "promocoes",
  LOGIN = "login",
  NONE = "",
  LOJA = "loja",
  FULL = "full",
}
