import { CategoriaProdutoEnum } from "../enums/CategoriaProdutoEnum";
import { SituacaoProdutoEnum } from "../enums/SituacaoProdutoEnum";

export const Mocks = {
  Categorias: [
    { id: 1, nome: "Infantil" },
    { id: 2, nome: "Educativos" },
    { id: 3, nome: "Andadores" },
    { id: 4, nome: "Jumpers" },
    { id: 5, nome: "Mobile" },
    // {id: 6, nome: "Brinquedos Bebês" },
    // {id: 7, nome: "Brinquedos para Festa" },
    // {id: 8, nome: "Cadeirinhas" },
    // {id: 9, nome: "Carrinhos/Bebê Conforto" },
    // {id: 10, nome: "Centro de Atividades" },
    // {id: 11, nome: "Educativos" },
    // {id: 12, nome: "Instrumentos Musicais" },
    // {id: 13, nome: "Jumperoo" },
    // {id: 14, nome: "Mesa de Atividades" },
    // { id: 15, nome: "Mini Veiculos" },
    // { id: 16, nome: "Mobile" },
    // { id: 17, nome: "Tapetes" },
    // { id: 18, nome: "Veículos Elétricos" },
  ],
  FaixaEtaria: [
    { id: 1, nome: "0 a 6 meses" },
    { id: 2, nome: "1 a 2 anos" },
    { id: 3, nome: "2 a 3 anos" },
    { id: 4, nome: "3 a 4 anos" },
    { id: 5, nome: "6 a 12 meses" },
    { id: 6, nome: "mais de 4 anos" },
  ],
  Cartoes: [
    {
      descricao: "Abelha follow...",
      imagem: "/assets/images/logo-okipoki_p.jpg",
      valor: 60,
      situacao: SituacaoProdutoEnum.DISPONIVEL,
    },
    {
      descricao: "Andador 3 em 1 com Luz...",
      imagem: "/assets/images/abelha.jpg",
      valor: 180,
      situacao: SituacaoProdutoEnum.DISPONIVEL,
    },
  ],
  Produtos: [
    {
      id: 1,
      nome: "Produto 1",
      descricao:
        "orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecatborum.",
      valor: 60,
      estoque: 3,
      imagem: "/assets/images/andador.jpeg",
      avaliacao: 2,
      valorDesconto: 0,
      situacao: SituacaoProdutoEnum.INDISPONIVEL,
      categoria: CategoriaProdutoEnum.EDUCATIVO,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 2,
      nome: "Produto 2",
      descricao:
        "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      valor: 60,
      estoque: 3,
      imagem: "/assets/images/abelha.jpg",
      avaliacao: 2,
      valorDesconto: 0,
      situacao: SituacaoProdutoEnum.DISPONIVEL,
      categoria: CategoriaProdutoEnum.EDUCATIVO,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 3,
      nome: "Abelha",
      descricao: "Abelha follow...",
      valor: 90,
      estoque: 3,
      valorDesconto: 0,
      imagem: "/assets/images/abelha.jpg",
      avaliacao: 2,
      situacao: SituacaoProdutoEnum.DISPONIVEL,
      categoria: CategoriaProdutoEnum.EDUCATIVO,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 4,
      nome: "Pula Pula",
      descricao: "Pula Pula",
      valor: 160,
      valorDesconto: 0,
      imagem: "/assets/images/abelha.jpg",
      categoria: CategoriaProdutoEnum.INFANTIL,
      situacao: SituacaoProdutoEnum.OFERTA,
      estoque: 5,
      avaliacao: 5,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 42,
      nome: "Pu3213213la Pula",
      descricao: "Pula Pula",
      valor: 160,
      valorDesconto: 0,
      imagem: "/assets/images/abelha.jpg",
      categoria: CategoriaProdutoEnum.INFANTIL,
      situacao: SituacaoProdutoEnum.OFERTA,
      estoque: 5,
      avaliacao: 5,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 45,
      nome: "Pu412414124la Pula",
      descricao: "Pula Pula",
      valor: 160,
      valorDesconto: 0,
      imagem: "/assets/images/abelha.jpg",
      categoria: CategoriaProdutoEnum.INFANTIL,
      situacao: SituacaoProdutoEnum.OFERTA,
      estoque: 5,
      avaliacao: 5,
      quantidade: 0,
      faixaEtaria: 6,
    },
    {
      id: 32,
      nome: "Pula P76565765ula",
      descricao: "Pula Pula",
      valor: 160,
      valorDesconto: 0,
      imagem: "/assets/images/abelha.jpg",
      categoria: CategoriaProdutoEnum.INFANTIL,
      situacao: SituacaoProdutoEnum.OFERTA,
      estoque: 5,
      avaliacao: 5,
      quantidade: 0,
      faixaEtaria: 6,
    },
  ],

  Descontos: [1, 0.05, 0.1, 0.15],
  Imagens: [
    "/assets/images/abelha.jpg",
    "/assets/images/andador.jpeg",
    "/assets/images/and1.jpeg",
    "/assets/images/and2.jpeg",
    "/assets/images/and4.jpeg",
  ],
};
